# ─ 데이터 경로 ─────────────────────────────────────────
data_dir: "dataset"         # hazy/ normal/ … 단일 폴더 구조

# ─ 데이터 분할 비율 ───────────────────────────────────
valtest_split: 0.30         # 전체의 30 %를 검증+테스트 세트로
seed: 1337

# ─ 입력 이미지 ───────────────────────────────────────
img_height: 224
img_width: 224
batch_size: 32

# ─ 학습 단계 ─────────────────────────────────────────
epochs_head: 20             # 특성 추출 단계
epochs_fine: 20             # 미세조정 단계

# ─ 학습률 ─────────────────────────────────────────────
initial_lr: 1.0e-3          # 헤드 학습
fine_tune_lr: 1.0e-4        # 미세조정

# ─ 베이스 모델 설정 ──────────────────────────────────
depth_multiplier: 1.0       # MobileNetV3 α (0.35-1.0)
unfreeze_from: 100          # 상위 N개 레이어만 학습 (fine-tune)
